Improve test step with pass/fail messaging
Enhance test step to provide feedback on test results.

diff --git a/.github/workflows/ciPatrik.yml b/.github/workflows/ciPatrik.yml
--- a/.github/workflows/ciPatrik.yml
+++ b/.github/workflows/ciPatrik.yml
@@ -29,7 +29,13 @@ jobs:
         run: dotnet build
 
       - name: Run Tests
-        run: dotnet test
+        run: |
+          if dotnet test; then
+          echo "Tests passed"
+          else
+          echo "Tests failed"
+          exit 1
+          fi
           
       #- name: Send to Discord
        # env:
